#!/usr/bin/python3

from chemRelease import info
import sys

camToQuint = {	'1A' : 'gismoll',
				'2A' : 'dismoll',
				'3A' : 'bmoll',
				'4A' : 'fmoll',
				'5A' : 'cmoll',
				'6A' : 'gmoll',
				'7A' : 'dmoll',
				'8A' : 'amoll',
				'9A' : 'emoll',
				'10A' : 'hmoll',
				'11A' : 'fismoll',
				'12A' : 'cismoll',
				'1B' : 'hdur',
				'2B' : 'fisdur',
				'3B' : 'desdur',
				'4B' : 'asdur',
				'5B' : 'esdur',
				'6B' : 'bdur',
				'7B' : 'fdur',
				'8B' : 'cdur',
				'9B' : 'gdur',
				'10B' : 'ddur',
				'11B' : 'adur',
				'12B' : 'edur',
				}

if ( len(sys.argv) > 1 ):
	catid = sys.argv[1]
	keys = info.key(catid)
	keys.fetch()

if ( keys.keys):
	for k in keys.keys:
		print( k + "\t" + camToQuint[k])
